name: ChatGPT Sprint Summary

on:
  schedule:
    - cron: '0 14 * * *'  # 每天 UTC 14:00 (台灣時間 22:00)
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Issues
        id: fetch_issues
        run: |
          issues=$(gh issue list --state open --limit 5 --json title,body)
          echo "issues=$issues" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Issues to ChatGPT
        id: chatgpt_request
        run: |
          response=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4",
              "messages": [{"role": "system", "content": "請根據以下的 GitHub Issues 內容，總結 Sprint 進度並提供回顧建議。"},
                           {"role": "user", "content": "'"${{ env.issues }}"'"}],
              "temperature": 0.7
            }')

          summary=$(echo $response | jq -r '.choices[0].message.content')
          echo "summary=$summary" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Save Summary as Markdown
        run: |
          SUMMARY_FILE="sprint-summary-$(date +'%Y-%m-%d').md"
          echo "## Sprint 回顧 - $(date +'%Y-%m-%d')" > $SUMMARY_FILE
          echo "" >> $SUMMARY_FILE
          echo "${{ env.summary }}" >> $SUMMARY_FILE
          echo "Markdown file saved as $SUMMARY_FILE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sprint-summary-*.md
          git commit -m "自動生成 Sprint 回顧報告 - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
