name: ChatGPT Sprint Summary

on:
  schedule:
    - cron: '0 14 * * *'  # 每天 UTC 22:00 執行 
  workflow_dispatch:  # 允許手動觸發

jobs:
  generate_summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Latest Issues
        id: fetch_issues
        run: |
          issues=$(gh issue list --state open --limit 5 --json title,body)
          echo "issues=$issues" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Issues to ChatGPT
        id: chatgpt_request
        run: |
          response=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4",
              "messages": [{"role": "system", "content": "請根據以下的 GitHub Issues 內容，總結 Sprint 進度並提供回顧建議。"},
                           {"role": "user", "content": "'"${{ env.issues }}"'"}],
              "temperature": 0.7
            }')

          summary=$(echo $response | jq -r '.choices[0].message.content')
          echo "summary=$summary" >> $GITHUB_ENV
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Create Sprint Summary Issue
        run: |
          gh issue create --title "[Sprint 回顧] $(date +'%Y-%m-%d')" --body "${{ env.summary }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
